sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product tstn-009
env:
  global:
    -
      # LTD_AWS_ID
      secure: pieY+Djqzk0mjFhzU+mxHVd6zCsicCNdKVPonVvfcGIaZRO/S2GrAdc+GV49h9EUgWTLq7KDmevFaX3gmWrMcIzNhTCsSzSHb5ESsNlLC8xjyTKBhoBYOdCH4zGMkvRnLCyqSS5r+wVZz7Fb5u+nAsP9TIQ3cpcyelUuDcoO06UjJ0FjsbbBKwmI2PRTffyLF3d2RU9Ug38Jv+fMyHM8tV6dDJN7AF7stsmq5IIERSFgHIUyIOQhiKSrFpBJK9BMbhyiUMPtpzGiktll0lbBZDOnnk4cxjxz7/Fh+0Ro+ySG3i+EQgwsxOVUpce9lqwXQ9uoCGVpiBHU1L/cYdJaXBCKVLD9XbXVWkiDwZgY0EpcSNA53GGgw1xOTUfA4JQWQtm1jPAIEDAiZeu0iH5jrGk28fFHl7tZM6AV2RBBegNlVDIHa8/ycNXrdwH1GpqXL5FTHlTarY2bcym/Fss0kKxY8qX/Ba/08efu/1wEdAE5A1djhuz2YryJbItuzwGnCIUXhAxu2kXjjnDcmX7H9Vx/BcXujM6QLPATAT0jq0OLsB2EEYjChfvNPc0mge/V5kcb+LqhnWjSjlIeVVouNW/1l+4fCUxWdS1Q0Jr2lr42ikKYr4tFxSiKzmPvnqWmJl41NeNPwolQfepFlAvpVAhEZCxtyrCRuujaXbYK1wA=
    -
      # LTD_AWS_SECRET
      secure: aSDBKsmp4q8bdJ3RW2TLeVBWtEah3hv9w5HrUnMggo8Nqf85AjF3FXI37KacGw4QCv6HGL9085Twai6BWBXoC0yhcFIwqQhLf8u/dqkhlmFqKcuJkXurv1Vw9ovs19Tx5lxjzT021tHY3WlOKMj9cozB7kV8o3gfyalVEJ8YMuNcDANri41nK/4QQALYcwphBptiGRi5rGnIvgLcs06NIJEj+G9A5Jvb07Nu+LnuB/F+DXnUssJ1L0FJ6eHN8j8icm6qZ5c3ujceR+2XA3QcwtpSjBKhkNwfClJp0OhMt08bAvqCGQ26ck9VNOHldBUwgCMXgxVMVSJqFa1IAvOSXIdNWvSqM13wmcX6c307l4VGFtR55Lqf7qlQqwetcakh7L+CzYBdXhDK0uVo30jE0HdU+LWvBovZOdNiA8dvF1ZhDEOVdWGfQBo2dO6DkGdYOLrkpU0ulwITer0jbSFCy5GUmiemRhUr6lbFEMp4V0siC2p4e1bvK6I7widdq8vuc4PkLWBXGm8yPiV9nR/6q1yvrvmBvvSvxGRzR2IbSINBXNlKSpDdgZeEC8fs28yzZIZF6RSZXi9imOoN3XIMSdFj2FZpHBDhtGO7bUuhBHgcL667xXTvQ+jTglqguMeuiUiAcDjyKcDVXlfAxzN57P3vK/Tj7tWdct+eB59BNCI=
    -
      # LTD_USERNAME
      secure: gXHAJq4ZU3G7Dg6iFRjZk1fdvW74v13xv+IF68kaskDdt2Fbt3xYEGmO0VJ1lKZFYfHQOnoem1biqWYDvxdftdKGJU1rHW4b3kEH+5B7ex6QZJW0sW56yTelxhf16jfEei9T03feJjyC1BqeHb1fpqBbqYY2is8LyPyfxLYpHkHuZgsj2PoEStp+25vnCGzzUw+NVBo0MKuwJV36B2YHMawkKjXaT1IgpBqbU+URP1x77W2pmnDmSm60PXFodRNbqeoBctZmPkTwapSNzTCkyyVUITr8gEfEr7ExEFM0F58uruas1dPKNvaopYLighneHQE0Kk6WFMUg1lmWtabn1aXm+Y1jFIun/rG9RVD+XFqr3gUQeFwZcwyscAMXqAYS0btOXEbF2FgyVUeuDxWi+VTYHX2Vm0Sac+DtczDU9NTKi36iuq8/mFgMI5DzUZicrAdzptEYWhqwhTbXw3sI1SoKo+X+SbatGzGCxyiwfgs8nuk3YXUGfXSPovb+8QSezOlgN6LbIYy4LoAs6od6ZkbiY35kK/n7bYAIIQMrKQQgkyPjKLyWRudVcsY5zTKdn6xm6JNLLd7ykDobIFnXTA0O2Dk6PAjD/9d7M2KkgM6OtR+G+z/QfSrN2BKoecX+Yso2/EyERHknEltao5cjVeS1gFAg3BRvlI25s+Btg3U=
    -
      # LTD_PASSWORD
      secure: QJnR+FDvHoA5x/vUcqHZHKSa4/nMmtTuEc+17o5qecAVh6eFaPO4TG4SeiSjdLj1GwP4plO5HOYe9NWhK3iQnanzdN0iS+wB0Z/dKMbcvggWkiMdmHNTqVb6d6v7PEfBmmx/oW2ny8GyB/5lkZZqEdvhYOJptV2QxBZaV5RrMv9vmMpp76IBTUbpl6Mzqw6dwxiHXTp8mWcZXDwT3/APVKlKtrWKUp6gHerGmvLPh70WjGIsFJgO5NPVH1oD/oLeY2XncAQ4PDH9O6KKxj0W5EjDzTTL0WnGhW+JFnWK1+Tk4oC3IDOl70fPniKq73OAlE0UeRTZU1jFuNCxu6OuFIH5Rdl3JoMLMvP0kGFhN2+QUf2VNs9fgj56fIfEzdF/5hXl7KK6UhpfQOTzrEJIy9bytUsht3c2H9zQLh8OmqqoNnJS541pp0rFrW5Tr7Rrm+p608f1iK9PFzWtglo3RdEy+8HCgjAd7ukKj4VPa13Ukl1lzmurz2NeaRkX4FBeMyX+p29txb7jUhgKM+Sxz5LbPrW4EP6qDpp14+FnsP+0nuKLCAUVMXDt9rCv6MJ0yPTbFSQespmQviL+Lg4HSNVGLjAC8nkfsnKIKXlUE2XV15KEk45UKd4teklGgW3wuUYwTA7g/h5YmkzZ5hibvLQoGU3ebHn5xs4fyj5Yubg=
